#%RAML 1.0 NamedExample
value:
  from: email-sapi@example.com
  to: gonzalo.marcos@mulesoft.com
  subject: "GON Inc - Your Order has been Completed"
  message: "Thanks for your order. We’ll let you know once your item(s) have dispatched. Your estimated delivery date is indicated below."