#%RAML 1.0 NamedExample
{
  "channel": {
    "email": false,
    "slack": true,
    "sms": true,
    "whatsapp": true
  },
  "messages": {
    "slack": {
      "channel": "mule-channel",
      "message": "Hello From the Slack System API!"
    }
  }
}