#%RAML 1.0 NamedExample
{
  "channel": {
    "email": true,
    "slack": true,
    "sms": false,
    "whatsapp": false
  },
  "messages": {
    "email": {
      "from": "no-reply@example.com",
      "to": "gmarcos@salesforce.com",
      "subject": "SUCCESS - Your email has arrived",
      "message": "This is an email from the Email sAPI"
    },
    "slack": {
      "channel": "mule-channel",
      "message": "Hello From the Slack System API!"
    }
  }
}