#%RAML 1.0 DataType
type: object
properties:
  channel: string
  message: string
examples:
  ex1: !include ../examples/SlackMessageExample1.raml
  ex2: !include ../examples/SlackMessageExample2.raml
  